### ISSUE TITLE
`ENM` node and edge counts should be counted after merging imports

### ISSUE THREAD

**Issue by jmillanacosta** [ncbo/kg-bioportal#99]
Hi, I came across this project and saw this:

![image](https://github.com/user-attachments/assets/bb08bf6d-56c8-473d-8e78-8ab57dfa220c)

The eNM ontology uses owl imports and you are probably only capturing the ontology annotations.

**Comment by caufieldjh** [comment]
Hi @jmillanacosta - excellent point! The transforms are not currently doing anything with imports, though [the corresponding Bioportal page](https://bioportal.bioontology.org/ontologies/ENM/?p=classes&conceptid=root) shows all base and imported classes. There are certainly positives and negatives about including imports, with one positive being that application ontologies like ENM will look much more complete with imports vs. without. In this case I can use one of the alternate serializations of the ontology as they contain the imported classes.

**Comment by jmillanacosta** [comment]
Hi @caufieldjh, thank you for your explanation, I think that's a good rule of thumb for application ontologies. However, we import a few hundred internally developed classes into the main `enanomapper.owl` class hierarchy that we would like to see reflected in the KG stats. I can get back to you soon when the next release is out to discuss which subset works better for this KG.
